### HW Questions (Numpy):

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

2. Find common elements between A and B. [Hint: Intersection of two sets]

3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
    url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
    iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])



In [23]:
#Answer 1
import numpy as np


A = np.array([[5, 6],
              [3, 4]])

B = np.array([[3, 4],
              [7, 8]])


V = np.vstack((A, B))


H = np.hstack((A, B))

print("A:\n", A)
print("B:\n", B)
print("Vertical stack (V):\n", V)
print("Horizontal stack (H):\n", H)

A:
 [[5 6]
 [3 4]]
B:
 [[3 4]
 [7 8]]
Vertical stack (V):
 [[5 6]
 [3 4]
 [3 4]
 [7 8]]
Horizontal stack (H):
 [[5 6 3 4]
 [3 4 7 8]]


In [13]:
#Answer 2
common = np.intersect1d(A, B)
print(common)

[3 4]


In [25]:
#Answer 3
mask = (A >= 5) & (A <= 10)
vals = A[mask]
print(vals)       


[5 6]


In [29]:
#Answer 4
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered = iris_2d[mask]

print(filtered.shape) 
print(filtered)        


(6, 4)
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### HW Questions (Pandas):
1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
    df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
   
2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
    df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

   
3. How to get the rows of a dataframe with row sum > 100?


   df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

   

In [35]:
#Answer 1
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

out = df.loc[::20, ['Manufacturer', 'Model', 'Type']].reset_index(drop=True)
print(out)



  Manufacturer    Model     Type
0        Acura  Integra    Small
1     Chrysler  LeBaron  Compact
2        Honda  Prelude   Sporty
3      Mercury   Cougar  Midsize
4       Subaru   Loyale    Small


In [47]:
#Answer 2
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

means = df[['Min.Price', 'Max.Price']].mean()


df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].fillna(means)


print(df[['Min.Price', 'Max.Price']].isna().sum())


Min.Price    0
Max.Price    0
dtype: int64


In [51]:
#Answer 3
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# rows where the sum across columns > 100
out = df[df.sum(axis=1) > 100]
print(out)


     0   1   2   3
1   31  31  22  27
4   18  18  31  35
5   21  39  14  34
6   29  19  24  39
7   16  36  32  31
12  33  35  21  18
13  26  38  32  14
14  35  30  20  17
